### ISSUE TITLE
Can't deploy Web Part on SharePoint Site

### ISSUE THREAD

**Issue by Rike89** [ravichandran-blog/SPFx#7]
I built the Web Part with Node 10.24.1
I used 
npm i
gulp build
gulp bundle --ship
gulp package-solution --ship

it all worked and I got my Sppkg-file.
Then I put it in the App-Catalouge
then I wanted to use the Web Part but ther was an Error that says:
FEHLER: 
Cannot read property 'latitude' of null

AUFRUFLISTE: 
TypeError: Cannot read property 'latitude' of null
    at t._getMapUrl (https://publiccdn.sharepointonline.com/dtshowcase.sharepoint.com/sites/apps/ClientSideAssets/9eaf4000-158d-45d6-91ed-7c3c2bc305e8/spfx-pnp-map-web-part_81fa33afbd4782f05f9c571746405ec3.js:1:312747)
    at t.render (https://publiccdn.sharepointonline.com/dtshowcase.sharepoint.com/sites/apps/ClientSideAssets/9eaf4000-158d-45d6-91ed-7c3c2bc305e8/spfx-pnp-map-web-part_81fa33afbd4782f05f9c571746405ec3.js:1:313185)
    at Da (https://modernb.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_de-de_6014a93328ffbc309a7ba3fee3e88452.js:65:414953)
    at Fa (https://modernb.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_de-de_6014a93328ffbc309a7ba3fee3e88452.js:65:414748)
    at mo (https://modernb.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_de-de_6014a93328ffbc309a7ba3fee3e88452.js:65:450530)
    at ou (https://modernb.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_de-de_6014a93328ffbc309a7ba3fee3e88452.js:65:441784)
    at iu (https://modernb.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_de-de_6014a93328ffbc309a7ba3fee3e88452.js:65:441709)
    at Go (https://modernb.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_de-de_6014a93328ffbc309a7ba3fee3e88452.js:65:438739)
    at Ko (https://modernb.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_de-de_6014a93328ffbc309a7ba3fee3e88452.js:65:435507)
    at Fu (https://modernb.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_de-de_6014a93328ffbc309a7ba3fee3e88452.js:65:456943)

what did I do wrong?

**Comment by P7162** [comment]
same here
